### ISSUE TITLE
Add generator to set up most of this

### ISSUE THREAD

**Issue by kentcdodds** [bahmutov/npm-module-checklist#9]
Checklists are helpful, but lots of this could be automated :-)

**Comment by bahmutov** [comment]
See, I was thinking about this, and not everything can be I feel like. Or at least people might come with this checklist later and as long as they use something - it would be good.

I actually saw a couple of generators, will include them into the check list.

**Comment by kentcdodds** [comment]
Cool. Yeah, I'm actually not a huge fan of generators I didn't write ;-) Context, personal preference, etc. I should just write one myself.

**Comment by iamstarkov** [comment]
as heavy yeoman generator developer consider to create your generator based on [node](https://github.com/yeoman/generator-node) or [nm](http://github.com/sindresorhus/generator-nm/). You can easily [extend them by using `this.composeWith`](http://yeoman.io/authoring/composability.html).

Will be happy to help

**Comment by jimthedev** [comment]
Small world. I just found this project but I am in the midst of writing a series of bash scripts to do this. It is OSX only, is super opinionated, half assed and has some global dependencies. It is called GiveMeJS and is very much in alpha/WIP. It is also missing a lot of things on this list. Anyhow I figured I'd mention it since it sounds like we have some overlapping goals. I love the straight forward nature of bash scripts but with the write api could see porting it to be a cross-OS JS lib or at least contributing to something like that.

https://github.com/jimthedev/givemejs
https://www.npmjs.com/package/givemejs

For now the only adapter is @staltz Cycle.js. More to come obviously.

**Comment by bahmutov** [comment]
I love generators, but the problem with a checklist covering so many tools - there is no generator versatile enough to setup everything up. There are no good enough generators to do most of these individually. I will add a section about generators (good idea, use them, ....) but to me the generators are "how", not "what" or "why".

**Comment by jimthedev** [comment]
@bahmutov I agree. The what and why need to come first. Any generators are just icing on the cake, but even then, they won't teach you much, they're just a shortcut for people that have already learned why this stuff is important. 

What do you mean "There are no good enough generators to do most of these individually."? Do you mean that in an ideal generator you'd be able to enable or disable any one of the items in the checklist?

**Comment by bahmutov** [comment]
@jimthedev I really don't like the shell scripts, goes against Nodejs

**Comment by bahmutov** [comment]
List of generators to consider (one can find more from yeoman project http://yeoman.io/generators/)
- `npm init`
- https://github.com/bucaran/generator-rise
- https://github.com/yeoman/generator-node
- https://github.com/ironSource/node-generator-nom
- https://github.com/yieme/generator-pkg
- https://github.com/sindresorhus/generator-nm

**Comment by iamstarkov** [comment]
maybe my generator also can be useful https://github.com/iamstarkov/generator-tiny-es-nm

**Comment by bahmutov** [comment]
sure, @iamstarkov can do

**Comment by kentcdodds** [comment]
I don't care about this anymore so I'm going to close it :)
